/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PresentationTier.Cliente;

import DataTier.Client.Client;
import DataTier.Packs.Datapack;
import LogicTier.InGame.Players.Player;
import LogicTier.InGame.WaterElements.Submarine;
import eu.hansolo.steelseries.gauges.DigitalRadial;
import eu.hansolo.steelseries.gauges.DisplayRectangular;
import eu.hansolo.steelseries.gauges.LinearBargraph;
import eu.hansolo.steelseries.gauges.Radial;
import eu.hansolo.steelseries.gauges.Radial1Square;
import eu.hansolo.steelseries.gauges.Radial2Top;
import eu.hansolo.steelseries.gauges.RadialCounter;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSlider;
import javax.swing.JTextArea;

/**
 *
 * @author Jose
 */
public class PantallaBienvenidaCliente extends javax.swing.JFrame {

    Client cliente;
    Datapack datapack; 

    LinearBargraph gaugeProfundidad;
    RadialCounter gaugeGrados;
    Radial2Top gaugeVelocidad;
    DigitalRadial gaugeVida;
    
    /**
     * Creates new form PantallaBienvenida
     */
     PantallaBienvenidaCliente(Datapack datapack){
         this.datapack = datapack; 
        
        
        gaugeProfundidad = new LinearBargraph();
        gaugeProfundidad.setTitle("Depth Units");
        gaugeProfundidad.setUnitString("100 Max U");
        
        gaugeGrados = new RadialCounter();
        gaugeGrados.setTitle("Grados");
        gaugeGrados.setUnitString("360 Max U");
        gaugeGrados.setMaxValue(360);
        gaugeGrados.setValueAnimated(360);
        
        gaugeVelocidad = new Radial2Top();
        gaugeVelocidad.setTitle("Speed");
        gaugeVelocidad.setUnitString("100 Max U");
        gaugeVelocidad.setMaxValue(100);
        
        gaugeVida = new DigitalRadial();
        gaugeVida.setMaxValue(10);
        
         
         
        initComponents();
        
          
        teamPanel2.playerDatapack = this.datapack;
        shop2.PlayerDatapack = this.datapack;  
        shop2.getLabel_balance().setText(datapack.player.points+"");
        radar.PlayerDatapack = datapack ;
        
        cliente = new Client();
        try {
           cliente.conexion(datapack, this);
           
        }
        catch(Exception e){
            System.out.println("Error de conexion cliente ---");
        }
    }


    // Getter para manejo externo de monitores

    public JLabel getCoordinates() {
        return coordinates;
    }

    public TeamPanel getTeamPanel() {
        return teamPanel2;
    }

    
    
    public JLabel getSpeed_monitorlabel() {
        return Speed_monitorlabel;
    }

    public JSlider getDepht_monitor() {
        return depht_monitor;
    }

    public JLabel getDepht_monitorlabel() {
        return depht_monitorlabel;
    }

    public JSlider getDirection_monitor() {
        return direction_monitor;
    }

    public JLabel getDirection_monitorlabel() {
        return direction_monitorlabel;
    }

    public radar getRadar() {
        return radar;
    }

    public JTextArea getjTextArea_monitor() {
        return jTextArea_monitor;
    }

    public JSlider getSpeed_monitor() {
        return speed_monitor;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new JPanel() {
            @Override
            public Dimension getPreferredSize() {
                return new Dimension(300, 300);
            }
        };
        jPanel4 = new JPanel() {
            @Override
            public Dimension getPreferredSize() {
                return new Dimension(300, 300);
            }
        };
        teamPanel2 = new PresentationTier.Cliente.TeamPanel();
        jPanel1 = new javax.swing.JPanel();
        direction_monitorlabel = new javax.swing.JLabel();
        Speed_monitorlabel = new javax.swing.JLabel();
        direction_label = new javax.swing.JLabel();
        depht_monitorlabel = new javax.swing.JLabel();
        depht_controler = new javax.swing.JScrollBar();
        radar = new PresentationTier.Cliente.radar();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        speed_controler = new javax.swing.JScrollBar();
        jLabel2 = new javax.swing.JLabel();
        direction_controler = new javax.swing.JScrollBar();
        direction_monitor = new javax.swing.JSlider();
        speed_monitor = new javax.swing.JSlider();
        depht_monitor = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_monitor = new javax.swing.JTextArea();
        button_chat = new javax.swing.JButton();
        text_chat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        coordinates = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        shop2 = new PresentationTier.Cliente.Shop();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );

        jPanel3.setLayout(new BorderLayout());
        jPanel3.add(gaugeVelocidad, BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel4.setLayout(new BorderLayout());
        jPanel4.add(gaugeVida, BorderLayout.CENTER);

        direction_monitorlabel.setText("jLabel3");

        Speed_monitorlabel.setText("jLabel3");

        direction_label.setText("direction");

        depht_monitorlabel.setText("jLabel3");

        depht_controler.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                depht_controlerAdjustmentValueChanged(evt);
            }
        });

        jLabel3.setText("0°");

        jLabel4.setText("90°");

        jLabel5.setText("180°");

        jLabel6.setText("270°");

        javax.swing.GroupLayout radarLayout = new javax.swing.GroupLayout(radar);
        radar.setLayout(radarLayout);
        radarLayout.setHorizontalGroup(
            radarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radarLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, radarLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(radarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(135, 135, 135))
        );
        radarLayout.setVerticalGroup(
            radarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, radarLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(radarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(108, 108, 108)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel1.setText("Depht");

        speed_controler.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                speed_controlerAdjustmentValueChanged(evt);
            }
        });

        jLabel2.setText("Speed");

        direction_controler.setMaximum(370);
        direction_controler.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        direction_controler.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                direction_controlerAdjustmentValueChanged(evt);
            }
        });

        direction_monitor.setMaximum(360);

        speed_monitor.setOrientation(javax.swing.JSlider.VERTICAL);

        depht_monitor.setOrientation(javax.swing.JSlider.VERTICAL);

        jTextArea_monitor.setColumns(20);
        jTextArea_monitor.setRows(5);
        jScrollPane1.setViewportView(jTextArea_monitor);

        button_chat.setText("Send");
        button_chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_chatActionPerformed(evt);
            }
        });

        jLabel7.setText("coordinate");

        coordinates.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(depht_monitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(depht_controler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(direction_label)
                                .addGap(39, 39, 39)
                                .addComponent(direction_monitorlabel))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(direction_monitor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(direction_controler, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(radar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(speed_controler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(depht_monitorlabel)
                                    .addGap(135, 135, 135)
                                    .addComponent(jLabel2)
                                    .addGap(53, 53, 53)
                                    .addComponent(Speed_monitorlabel))))
                        .addGap(18, 18, 18)
                        .addComponent(speed_monitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(text_chat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_chat)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(coordinates)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_chat)
                    .addComponent(text_chat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(coordinates))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(Speed_monitorlabel)
                    .addComponent(depht_monitorlabel))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(speed_monitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(speed_controler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(depht_controler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(depht_monitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direction_label)
                    .addComponent(direction_monitorlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direction_controler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(direction_monitor, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setText("Tienda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teamPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(shop2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(teamPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(28, 28, 28)
                        .addComponent(shop2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(275, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depht_controlerAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_depht_controlerAdjustmentValueChanged
        int depht = depht_controler.getValue(); 
        datapack.self.control_depht = depht; 
    }//GEN-LAST:event_depht_controlerAdjustmentValueChanged

    private void speed_controlerAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_speed_controlerAdjustmentValueChanged
        int speed = speed_controler.getValue(); 
        datapack.self.control_speed = speed; 
    }//GEN-LAST:event_speed_controlerAdjustmentValueChanged

    private void direction_controlerAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_direction_controlerAdjustmentValueChanged
        int direction = direction_controler.getValue();
        datapack.self.control_direction =  direction; 
    }//GEN-LAST:event_direction_controlerAdjustmentValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tienda().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button_chatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_chatActionPerformed
        
    }//GEN-LAST:event_button_chatActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Speed_monitorlabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_chat;
    private javax.swing.JLabel coordinates;
    private javax.swing.JScrollBar depht_controler;
    private javax.swing.JSlider depht_monitor;
    private javax.swing.JLabel depht_monitorlabel;
    private javax.swing.JScrollBar direction_controler;
    private javax.swing.JLabel direction_label;
    private javax.swing.JSlider direction_monitor;
    private javax.swing.JLabel direction_monitorlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_monitor;
    private PresentationTier.Cliente.radar radar;
    private PresentationTier.Cliente.Shop shop2;
    private javax.swing.JScrollBar speed_controler;
    private javax.swing.JSlider speed_monitor;
    private PresentationTier.Cliente.TeamPanel teamPanel2;
    private javax.swing.JTextField text_chat;
    // End of variables declaration//GEN-END:variables
}
