/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationTier.Cliente;

import DataTier.Packs.Datapack;
import java.util.concurrent.ExecutionException;
import javax.swing.JLabel;

/**
 *
 * @author Leonardo
 */
public class Shop extends javax.swing.JPanel {

    Datapack PlayerDatapack;

    /**
     * Creates new form Shop
     */
    public Shop() {
        initComponents();
        combo_propeller.removeAllItems();

        combo_propeller.addItem(0);
        combo_propeller.addItem(0.3);
        combo_propeller.addItem(0.7);
        combo_propeller.addItem(1);
        combo_radar.removeAllItems();

        combo_radar.addItem(0);
        combo_radar.addItem(50000);
        combo_radar.addItem(100000);
        combo_radar.addItem(150000);
        combo_radar.addItem(200000);
        combo_radar.addItem(250000);
        combo_radar.addItem(300000);
        combo_radar.addItem(800000);

        comorudder.removeAllItems();
        comorudder.addItem(0);
        comorudder.addItem(0.3);
        comorudder.addItem(0.7);
        comorudder.addItem(1);
        
        combo_inmercion.removeAllItems();
        combo_inmercion.addItem(0);
        combo_inmercion.addItem(0.3);
        combo_inmercion.addItem(0.7);
        combo_inmercion.addItem(1);



    }

    public JLabel getLabel_balance() {
        return label_balance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        combo_radar = new javax.swing.JComboBox();
        buy_radar = new javax.swing.JButton();
        combo_propeller = new javax.swing.JComboBox();
        buy_propeller = new javax.swing.JButton();
        comorudder = new javax.swing.JComboBox();
        buy_rudder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buy_torpedo = new javax.swing.JButton();
        combo_torpedo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label_balance = new javax.swing.JLabel();
        price_radar = new javax.swing.JLabel();
        Price_propeller = new javax.swing.JLabel();
        price_rudder = new javax.swing.JLabel();
        price_torpedo = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Inmecion = new javax.swing.JLabel();
        combo_inmercion = new javax.swing.JComboBox();
        price_inmercion = new javax.swing.JLabel();
        buy_inmericion = new javax.swing.JButton();

        jLabel14.setText("jLabel10");

        combo_radar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_radar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_radarActionPerformed(evt);
            }
        });

        buy_radar.setText("Buy");
        buy_radar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy_radarActionPerformed(evt);
            }
        });

        combo_propeller.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_propeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_propellerActionPerformed(evt);
            }
        });

        buy_propeller.setText("Buy");
        buy_propeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy_propellerActionPerformed(evt);
            }
        });

        comorudder.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comorudder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comorudderActionPerformed(evt);
            }
        });

        buy_rudder.setText("Buy");
        buy_rudder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy_rudderActionPerformed(evt);
            }
        });

        jLabel1.setText("Radar / Comunicator");

        jLabel2.setText("Propeller");

        jLabel4.setText("Rudder");

        jLabel6.setText("Torpedo");

        buy_torpedo.setText("Buy");

        combo_torpedo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_torpedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_torpedoActionPerformed(evt);
            }
        });

        jLabel7.setText("Shop");

        jLabel8.setText("Balance:");

        label_balance.setText("jLabel9");

        price_radar.setText("jLabel10");

        Price_propeller.setText("jLabel10");

        price_rudder.setText("jLabel10");

        price_torpedo.setText("jLabel10");

        jLabel15.setText("Price:");

        jLabel16.setText("Item");

        Inmecion.setText("Inmercion");

        combo_inmercion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_inmercion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_inmercionActionPerformed(evt);
            }
        });

        price_inmercion.setText("jLabel9");

        buy_inmericion.setText("Buy");
        buy_inmericion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy_inmericionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_radar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(price_radar))))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(Inmecion)
                            .addComponent(combo_inmercion, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comorudder, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combo_propeller, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combo_torpedo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Price_propeller)
                                .addComponent(price_rudder))
                            .addComponent(price_torpedo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(price_inmercion))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(buy_propeller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buy_rudder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buy_torpedo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buy_inmericion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(buy_radar))
                        .addGap(22, 22, 22))))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addGap(66, 66, 66)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_balance)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(label_balance))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel3)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo_radar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buy_radar)
                            .addComponent(price_radar))
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buy_torpedo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(combo_propeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buy_propeller)
                                    .addComponent(Price_propeller))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comorudder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buy_rudder)
                                    .addComponent(price_rudder))
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(combo_torpedo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(price_torpedo))
                                .addGap(3, 3, 3)))
                        .addComponent(Inmecion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo_inmercion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buy_inmericion)
                            .addComponent(price_inmercion))
                        .addGap(10, 10, 10))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combo_radarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_radarActionPerformed
        try {
            price_radar.setText("" + (int) (Double.parseDouble(combo_radar.getSelectedItem().toString()) * 0.0023));
        } catch (Exception x) {

        }


    }//GEN-LAST:event_combo_radarActionPerformed

    private void combo_propellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_propellerActionPerformed
        try {
            Price_propeller.setText("" + (int) (Double.parseDouble(combo_propeller.getSelectedItem().toString()) * 15.0));
        } catch (Exception x) {

        }

    }//GEN-LAST:event_combo_propellerActionPerformed

    private void comorudderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comorudderActionPerformed
        try {
            price_rudder.setText("" + (int) (Double.parseDouble(comorudder.getSelectedItem().toString()) * 40.0));
        } catch (Exception x) {

        }
    }//GEN-LAST:event_comorudderActionPerformed

    private void combo_torpedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_torpedoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_torpedoActionPerformed

    private void buy_radarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy_radarActionPerformed
        int price = Integer.parseInt(price_radar.getText());
         if (price <= PlayerDatapack.player.points) {
        PlayerDatapack.player.points -= price;
        PlayerDatapack.self.radar_efficiency = Integer.parseInt(combo_radar.getSelectedItem().toString());

        label_balance.setText(PlayerDatapack.player.points + "");
         }
    }//GEN-LAST:event_buy_radarActionPerformed

    private void buy_propellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy_propellerActionPerformed

        int price = Integer.parseInt(Price_propeller.getText());
        if (price <= PlayerDatapack.player.points) {
            PlayerDatapack.player.points -= price;
            PlayerDatapack.self.propeller_efficiency = Double.parseDouble(combo_propeller.getSelectedItem().toString());
            label_balance.setText(PlayerDatapack.player.points + "");
        }
    }//GEN-LAST:event_buy_propellerActionPerformed

    private void buy_rudderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy_rudderActionPerformed
        int price = Integer.parseInt(price_rudder.getText());
        if (price <= PlayerDatapack.player.points) {
            PlayerDatapack.player.points -= price;
            PlayerDatapack.self.rudder_efficiency = Double.parseDouble(comorudder.getSelectedItem().toString());
            label_balance.setText(PlayerDatapack.player.points + "");
        }
    }//GEN-LAST:event_buy_rudderActionPerformed

    private void combo_inmercionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_inmercionActionPerformed
       try {
            price_inmercion.setText("" + (int) (Double.parseDouble(combo_inmercion.getSelectedItem().toString()) * 100.0));
        } catch (Exception x) {

        }    }//GEN-LAST:event_combo_inmercionActionPerformed

    private void buy_inmericionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy_inmericionActionPerformed
    int price = Integer.parseInt(price_inmercion.getText());
        if (price <= PlayerDatapack.player.points) {
            PlayerDatapack.player.points -= price;
            PlayerDatapack.self.inmersion_efficiency = Double.parseDouble(combo_propeller.getSelectedItem().toString());
            label_balance.setText(PlayerDatapack.player.points + "");
        }    }//GEN-LAST:event_buy_inmericionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Inmecion;
    private javax.swing.JLabel Price_propeller;
    private javax.swing.JButton buy_inmericion;
    private javax.swing.JButton buy_propeller;
    private javax.swing.JButton buy_radar;
    private javax.swing.JButton buy_rudder;
    private javax.swing.JButton buy_torpedo;
    private javax.swing.JComboBox combo_inmercion;
    private javax.swing.JComboBox combo_propeller;
    private javax.swing.JComboBox combo_radar;
    private javax.swing.JComboBox combo_torpedo;
    private javax.swing.JComboBox comorudder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel label_balance;
    private javax.swing.JLabel price_inmercion;
    private javax.swing.JLabel price_radar;
    private javax.swing.JLabel price_rudder;
    private javax.swing.JLabel price_torpedo;
    // End of variables declaration//GEN-END:variables
}
