/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationTier.Cliente;

import LogicTier.InGame.Players.Player;
import LogicTier.InGame.Players.Team;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JList;

/**
 *
 * @author Leo
 */
public class TeamPanel extends javax.swing.JPanel {

    ArrayList<Team> playerTeam; 
    Player currentPlayer; 
    
    /**
     * Creates new form Team
     */
    public TeamPanel() {
        initComponents();
        Combo_TeamList.removeAllItems();
        list_requestList.removeAll();
        list_teamMembers.removeAll();
        
    }

    public JComboBox getCombo_TeamList() {
        return Combo_TeamList;
    }

    public void setCombo_TeamList(JComboBox Combo_TeamList) {
        this.Combo_TeamList = Combo_TeamList;
    }

    public JList getList_requestList() {
        return list_requestList;
    }

    public void setList_requestList(JList list_requestList) {
        this.list_requestList = list_requestList;
    }

    public JList getList_teamMembers() {
        return list_teamMembers;
    }

    public void setList_teamMembers(JList list_teamMembers) {
        this.list_teamMembers = list_teamMembers;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_teamMembers = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jPanel_MyTeamDef = new javax.swing.JPanel();
        Combo_TeamList = new javax.swing.JComboBox();
        text_creatteam = new javax.swing.JTextField();
        button_creatteam = new javax.swing.JButton();
        button_jointeam = new javax.swing.JButton();
        jPanel_teamManager = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_requestList = new javax.swing.JList();
        button_acceptPlayer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        list_teamMembers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_teamMembers);

        jLabel1.setText("My team");

        Combo_TeamList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        text_creatteam.setText("Team Name");
        text_creatteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_creatteamActionPerformed(evt);
            }
        });

        button_creatteam.setText("Creat");
        button_creatteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_creatteamActionPerformed(evt);
            }
        });

        button_jointeam.setText("Join");
        button_jointeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_jointeamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_MyTeamDefLayout = new javax.swing.GroupLayout(jPanel_MyTeamDef);
        jPanel_MyTeamDef.setLayout(jPanel_MyTeamDefLayout);
        jPanel_MyTeamDefLayout.setHorizontalGroup(
            jPanel_MyTeamDefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MyTeamDefLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_MyTeamDefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_creatteam)
                    .addComponent(Combo_TeamList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_MyTeamDefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_jointeam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_creatteam, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel_MyTeamDefLayout.setVerticalGroup(
            jPanel_MyTeamDefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MyTeamDefLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_MyTeamDefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Combo_TeamList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_jointeam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_MyTeamDefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_creatteam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_creatteam))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        list_requestList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(list_requestList);

        button_acceptPlayer.setText("Acept player");

        jLabel3.setText("Team requests");

        javax.swing.GroupLayout jPanel_teamManagerLayout = new javax.swing.GroupLayout(jPanel_teamManager);
        jPanel_teamManager.setLayout(jPanel_teamManagerLayout);
        jPanel_teamManagerLayout.setHorizontalGroup(
            jPanel_teamManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_teamManagerLayout.createSequentialGroup()
                .addGroup(jPanel_teamManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_teamManagerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_teamManagerLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel_teamManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button_acceptPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_teamManagerLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(247, 247, 247)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_teamManagerLayout.setVerticalGroup(
            jPanel_teamManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_teamManagerLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_acceptPlayer))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_teamManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_MyTeamDef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel_MyTeamDef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_teamManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void text_creatteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_creatteamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_creatteamActionPerformed

    private void button_creatteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_creatteamActionPerformed
        Team newTeam = new Team(text_creatteam.getText(), currentPlayer); 
        playerTeam.add(newTeam); 
    }//GEN-LAST:event_button_creatteamActionPerformed

    private void button_jointeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_jointeamActionPerformed
        Team joiningTeam = (Team) Combo_TeamList.getSelectedItem(); 
        joiningTeam.request.add(currentPlayer); 
    }//GEN-LAST:event_button_jointeamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Combo_TeamList;
    private javax.swing.JButton button_acceptPlayer;
    private javax.swing.JButton button_creatteam;
    private javax.swing.JButton button_jointeam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel_MyTeamDef;
    private javax.swing.JPanel jPanel_teamManager;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList list_requestList;
    private javax.swing.JList list_teamMembers;
    private javax.swing.JTextField text_creatteam;
    // End of variables declaration//GEN-END:variables
}
